### ISSUE TITLE
Typo in MWS

### ISSUE THREAD

**Issue by MariaHei** [dosc91/LDLConvFunctions#2]
Hi :) Very handy package! I think I found a small typo in `MWS` in [this line](https://github.com/dosc91/LDLConvFunctions/blob/133770cae40125d3849d44459cfead6c6443e553/R/MWS.R#L22). It should be just `prod_acc`, as in the function's parameter list, not `combined.prod_acc` (which is probably a global variable in your code?).

**Comment by dosc91** [comment]
Hi!

Yes, indeed, this is a typo. Thanks for bringing this up; I will fix it later today.

**Comment by dosc91** [comment]
Fixed it, closing this issue. Thanks again for spotting it! :-)
